### ISSUE TITLE
Testagem automática do back

### ISSUE THREAD

**Issue by gabsrp2002** [MatheusHenriqueSS/maratonic#8]
- criar casos de testes unitários e e2e para cada feature do back
- ter um test-coverage de no mínimo 80%
- a alteração só pode subir para produção se passar em todos os casos de teste e tiver casos de teste próprios criados

**Comment by brenofranca83** [comment]
Isso não é feature, ok pessoal? Teste é parte do processo... o teste deveria testar uma feature, essa sim é o que eu estava esperando.

**Comment by brenofranca83** [comment]
O PR associado aqui é o mesmo da #4
